import * as dotenv from 'dotenv';
import { DEFAULT_ENV } from 'src/config/env/default/default.env';
dotenv.config();

export const PROD_ENV = {
    // AMBIENTE DE EJECUCION
    NODE_ENV : process.env.NODE_ENV || DEFAULT_ENV.NODE_ENV,
    // PUERTO SERVIDOR
    SERVER_PORT : process.env.SERVER_PORT || DEFAULT_ENV.SERVER_PORT,
    // DATA BASE
    DATABASE_TYPE : process.env.DATABASE_TYPE || DEFAULT_ENV.DATABASE_TYPE,
    DATABASE_HOST : process.env.DATABASE_HOST || DEFAULT_ENV.DATABASE_HOST,
    DATABASE_PORT : process.env.DATABASE_PORT || DEFAULT_ENV.DATABASE_PORT,
    DATABASE_USERNAME : process.env.DATABASE_USERNAME || DEFAULT_ENV.DATABASE_USERNAME,
    DATABASE_PASSWORD : process.env.DATABASE_PASSWORD || DEFAULT_ENV.DATABASE_PASSWORD,
    DATABASE_NAME : process.env.DATABASE_NAME || DEFAULT_ENV.DATABASE_NAME,
    // KEY SECRET
    JWT_SECRET : process.env.JWT_SECRET || DEFAULT_ENV.JWT_SECRET,
    // USER DEFAULT
    ADMIN_USER : process.env.ADMIN_USER || DEFAULT_ENV.ADMIN_USER,
    ADMIN_USER_EMAIL : process.env.ADMIN_USER_EMAIL || DEFAULT_ENV.ADMIN_USER_EMAIL,
    ADMIN_USER_PASSWORD : process.env.ADMIN_USER_PASSWORD || DEFAULT_ENV.ADMIN_USER_PASSWORD,
    // PATH ROOT STORAGE
    PATH_ROOT_STORAGE : process.env.PATH_ROOT_STORAGE || DEFAULT_ENV.PATH_ROOT_STORAGE,
    // LIST WHITE CORS
    CORS_WHITELIST : process.env.CORS_WHITELIST || DEFAULT_ENV.CORS_WHITELIST,
};
