import * as dotenv from 'dotenv';
dotenv.config();
import { DEFAULT_ENV } from '../default/default.env';

//ENTORNO DE ARRANQUE DEL SERVIDOR
export const ENV = {
    NODE_ENV : process.env.NODE_ENV || DEFAULT_ENV.NODE_ENV,
    SERVER_PORT : process.env.SERVER_PORT || DEFAULT_ENV.SERVER_PORT,
    DATABASE_TYPE : process.env.DATABASE_TYPE || DEFAULT_ENV.DATABASE_TYPE,
    DATABASE_HOST : process.env.DATABASE_HOST || DEFAULT_ENV.DATABASE_HOST,
    DATABASE_PORT : process.env.DATABASE_PORT || DEFAULT_ENV.DATABASE_PORT,
    DATABASE_USERNAME : process.env.DATABASE_USERNAME || DEFAULT_ENV.DATABASE_USERNAME,
    DATABASE_PASSWORD : process.env.DATABASE_PASSWORD || DEFAULT_ENV.DATABASE_PASSWORD,
    DATABASE_NAME : process.env.DATABASE_NAME || DEFAULT_ENV.DATABASE_NAME,
    JWT_SECRET : process.env.JWT_SECRET || DEFAULT_ENV.JWT_SECRET,
    DEFAULT_USER : process.env.DEFAULT_USER || DEFAULT_ENV.DEFAULT_USER,
    DEFAULT_USER_EMAIL : process.env.DEFAULT_USER_EMAIL || DEFAULT_ENV.DEFAULT_USER_EMAIL,
    DEFAULT_USER_PASSWORD : process.env.DEFAULT_USER_PASSWORD || DEFAULT_ENV.DEFAULT_USER_PASSWORD,
    PATH_API_FILES : process.env.PATH_API_FILES || DEFAULT_ENV.PATH_API_FILES,
    CORS_WHITELIST : process.env.CORS_WHITELIST || DEFAULT_ENV.CORS_WHITELIST,
}